package de.healthai.eatelligent.data

import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * Represents the structured nutrition information generated by the OpenAI analysis.
 */
data class MealAnalysis(
    val description: String,
    val fatGrams: Double,
    val carbGrams: Double,
    val proteinGrams: Double
)

/**
 * Persisted meal entry that is stored locally as JSON.
 */
data class MealEntry(
    val id: String,
    val recordedAt: Instant,
    val description: String,
    val fatGrams: Double,
    val carbGrams: Double,
    val proteinGrams: Double,
    val imageBase64: String? = null
) {
    val calories: Double
        get() = (fatGrams * 9) + (carbGrams * 4) + (proteinGrams * 4)

    fun formattedTimestamp(): String = recordedAt.atZone(ZoneId.systemDefault())
        .format(DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm"))

    companion object {
        val formatter: DateTimeFormatter = DateTimeFormatter.ISO_INSTANT
    }
}
